{% set version = "10.7.0" %}

package:
  name: armadillo
  version: {{ version }}

source:
  fn: armadillo-{{ version }}.tar.xz
  url: http://sourceforge.net/projects/arma/files/armadillo-{{ version }}.tar.xz
  sha256: 9bf60db6fd237721908747a0e56797b97b7ceae3603f2cca0b012a3b88265d3f

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('armadillo', min_pin='x.x', max_pin='x') }}

requirements:
  build:
    - cmake >=3.1
    - make  # [unix]
    - {{ compiler('cxx') }}
    - pkg-config  # [unix]
    - ninja  # [win]
  host:
    # optional items below here
    - libblas
    - liblapack
    - arpack  # [unix]
    - superlu >=5.2.0,<6  # [unix]
  run:
    - arpack  # [unix]
    - superlu >=5.2.0,<6  # [unix]

test:
  commands:
    - test -f "${PREFIX}/include/armadillo"  # [unix]
    - test -d "${PREFIX}/include/armadillo_bits"  # [unix]
    - test -f "${PREFIX}/lib/libarmadillo${SHLIB_EXT}"  # [unix]
    - if not exist %LIBRARY_INC%\armadillo_bits exit 1  # [win]
    - if not exist %LIBRARY_INC%\armadillo exit 1  # [win]
    - if not exist %LIBRARY_LIB%\armadillo.lib exit 1  # [win]

about:
  home: http://arma.sourceforge.net
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Armadillo C++ linear algebra library

extra:
  recipe-maintainers:
    - grlee77
    - dirmeier
    - marcelotrevisani
    - henryiii
