{% set version = "8.200.0" %}
{% set variant = "openblas" %}

package:
    name: armadillo
    version: {{ version }}

source:
    fn: armadillo-{{ version }}.tar.xz
    url: http://sourceforge.net/projects/arma/files/armadillo-{{ version }}.tar.xz
    sha256: 998d4c689fe5c18e393a5d129aa5d1fd649592ae1a94e0c280d3f88e01526aa8
    patches:
        # have to add additional ${PREFIX}/lib etc... to tests/Makefile
        - make_tests.patch  # [linux]
        - make_tests_osx.patch  # [osx]
        # modify CMakeLists to use OpenBLAS rather than Accelrate on OS X
        # and to use OpenBLAS as the LAPACK library on linux
        - CMakeLists.patch

build:
  number: 200
  skip: True  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cmake
    # optional items below here
    - pkg-config
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - arpack
    - superlu 5*
    # - hdf5 1.8.17|1.8.17.*
  run:
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - arpack
    - superlu 5*
    # - hdf5 1.8.17|1.8.17.*

test:
  commands:
    - test -f "${PREFIX}/include/armadillo"
    - test -d "${PREFIX}/include/armadillo_bits"
    - test -f "${PREFIX}/lib/libarmadillo.so"  # [linux]
    - test -f "${PREFIX}/lib/libarmadillo.dylib"  # [osx]

about:
    home: http://arma.sourceforge.net
    license: Apache 2.0
    license_file: LICENSE.txt
    summary: Armadillo C++ linear algebra library

extra:
    recipe-maintainers:
      - grlee77
      - dirmeier
