{% set version = "9.700.2" %}

package:
    name: armadillo
    version: {{ version }}

source:
    fn: armadillo-{{ version }}.tar.xz
    url: http://sourceforge.net/projects/arma/files/armadillo-{{ version }}.tar.xz
    sha256: 923f2b48974f707c9da3176aab8d370e8003de23277c17ca0e49fdf97fac08bd
    patches:
        # have to add additional ${PREFIX}/lib etc... to tests/Makefile
        - make_tests.patch  # [linux]
        - make_tests_osx.patch  # [osx]
        # modify CMakeLists to use OpenBLAS rather than Accelrate on OS X
        # and to use OpenBLAS as the LAPACK library on linux
        - CMakeLists.patch  # [unix]

build:
  number: 1204
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('armadillo', min_pin='x.x', max_pin='x') }}

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - pkg-config  # [unix]
  host:
    # optional items below here
    - libblas
    - liblapack
    - arpack  # [unix]
    - superlu 5.2.*  # [unix]
  run:
    - arpack  # [unix]
    - superlu 5.2.*  # [unix]

test:
  commands:
    - test -f "${PREFIX}/include/armadillo"  # [unix]
    - test -d "${PREFIX}/include/armadillo_bits"  # [unix]
    - test -f "${PREFIX}/lib/libarmadillo${SHLIB_EXT}"  # [unix]
    - if not exist %LIBRARY_INC%\armadillo_bits exit 1  # [win]
    - if not exist %LIBRARY_INC%\armadillo exit 1  # [win]
    - if not exist %LIBRARY_LIB%\armadillo.lib exit 1  # [win]

about:
    home: http://arma.sourceforge.net
    license: Apache 2.0
    license_file: LICENSE.txt
    summary: Armadillo C++ linear algebra library

extra:
    recipe-maintainers:
      - grlee77
      - dirmeier
      - marcelotrevisani
