schema_version: 1

context:
  version: 15.2.1

package:
  name: armadillo
  version: ${{ version }}

source:
  url: https://netcologne.dl.sourceforge.net/project/arma/armadillo-${{ version }}.tar.xz?viasf=1
  sha256: a5b8109da3c169802f51a14d3bd1246395c24bbca55601760b0c96a3c0b2f8fa

build:
  number: 1
  skip: win and vc<14

requirements:
  build:
    - cmake >=3.1
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: unix
      then:
        - make
        - pkg-config
    - if: win
      then: ninja
  host:
    # optional items below here
    - libblas
    - liblapack
    - if: unix
      then:
       - arpack
       - superlu <7.1
  run:
    - if: unix
      then:
        - arpack
        - superlu <7.1
  run_exports:
    - ${{ pin_subpackage('armadillo', lower_bound='x.x', upper_bound='x') }}

tests:
  - script:
      - if: unix
        then:
          - test -f "${PREFIX}/include/armadillo"
          - test -d "${PREFIX}/include/armadillo_bits"
          - test -f "${PREFIX}/lib/libarmadillo${SHLIB_EXT}"
      - if: win
        then:
          - if not exist %LIBRARY_INC%\armadillo_bits exit 1
          - if not exist %LIBRARY_INC%\armadillo exit 1
          - if not exist %LIBRARY_LIB%\armadillo.lib exit 1

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Armadillo C++ linear algebra library
  homepage: http://arma.sourceforge.net

extra:
  recipe-maintainers:
    - grlee77
    - dirmeier
    - marcelotrevisani
    - henryiii
