schema_version: 1

context:
  version: 15.2.0

package:
  name: armadillo
  version: ${{ version }}

source:
  url: http://sourceforge.net/projects/arma/files/armadillo-${{ version }}.tar.xz
  sha256: fc5c2237c73e24411ff30e9c90aef8f756c462320c736c3862aa66b1a56ee9ce
  file_name: armadillo-${{ version }}.tar.xz

build:
  number: 1
  skip: win and vc<14

requirements:
  build:
    - cmake >=3.1
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: unix
      then:
        - make
        - pkg-config
    - if: win
      then: ninja
  host:
    # optional items below here
    - libblas
    - liblapack
    - if: unix
      then:
       - arpack
       - superlu <7.1
  run:
    - if: unix
      then:
        - arpack
        - superlu <7.1
  run_exports:
    - ${{ pin_subpackage('armadillo', lower_bound='x.x', upper_bound='x') }}

tests:
  - script:
      - if: unix
        then:
          - test -f "${PREFIX}/include/armadillo"
          - test -d "${PREFIX}/include/armadillo_bits"
          - test -f "${PREFIX}/lib/libarmadillo${SHLIB_EXT}"
      - if: win
        then:
          - if not exist %LIBRARY_INC%\armadillo_bits exit 1
          - if not exist %LIBRARY_INC%\armadillo exit 1
          - if not exist %LIBRARY_LIB%\armadillo.lib exit 1

about:
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Armadillo C++ linear algebra library
  homepage: http://arma.sourceforge.net

extra:
  recipe-maintainers:
    - grlee77
    - dirmeier
    - marcelotrevisani
    - henryiii
