appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: nD40AviIDbObtD2PXPEakg/9Lv0uIJCwnUFFh+zVIHb6s4wfugAfnp8EaQ93xwmsuWmzBaqN3qfSkry84ODt4YhfJ2HBcYllrUiH9PVnvYvC2FUyapcUnLSiKy+xg8GX4Nax5G1qu0DfREbMwaMYbim7NZQ+6LdoUih2Fx77RgoO9z8Y3eHFSnyKjzSnGIj5AyLYLVXqcyKyuR8D1K2J72Rg3A5ugAKjDlkpCjU2xCq6jVJ/mfM82olbksJpg+GxOe+5G7Erz0bAwPgm31VA2ITcwt0G2VvEZK7V06bslZMTeOJmkb+gqB+97jpEgqkSTir3AheqkN2MpzpQdhZOM15WEE5M4zvFYq7HKqNEZCJGnd6/N9VMPu/70MIvTxFfvu43jAxKA/KyZQC4oH0/Sae+lcueAiHfq+5S3LS6Fa5rDVDyuVxDWBJ46mtB8YKgH7lb/hJDY0XWy+rbcusb2WLixJ1Qae9uxbJ1uc9jiEs37yHaMmJ+Xi0IITtUMp2LwfmU2BG/4KSuGWOl7gpVLSCQvQ/gxi1Rea1wyUNRTHAD80/hN7s/7WeO8CWDD0SoGOc6WNdn0Ny8gwMMh0lSwRIbnvG6mdj8UlTCU9hIdKZ+6yqA3+yb3GuCw2hBKiMWkZerOfx276QyJSUaFaTAKXA8PH4RNHir9YGmmhu8Mws=}
